Tor har file bug  require k.encode("utf-8")
Came across the error 
headers = {k: v for k, v in headers.items() if is_legal_header_name(k)}
TypeError: cannot use a bytes pattern on a string-like object

This pull request fixes this issue